use std::sync::{Arc, Mutex};
use std::thread;
use std::time::Duration;

use x11rb::connection::Connection;
use x11rb::protocol::Event;
use x11rb::protocol::xproto::{
    AtomEnum, ConnectionExt as XProtoConnectionExt, CreateWindowAux, EventMask, PropMode,
    SelectionNotifyEvent, SelectionRequestEvent, WindowClass,
};
use x11rb::rust_connection::RustConnection;
use x11rb::wrapper::ConnectionExt;

struct SelectionState {
    text: String,
    version: u64,
    release: bool,
}

pub struct PrimarySelection {
    state: Arc<Mutex<SelectionState>>,
    handle: Option<thread::JoinHandle<()>>,
}

impl PrimarySelection {
    pub fn new() -> Self {
        Self {
            state: Arc::new(Mutex::new(SelectionState {
                text: String::new(),
                version: 0,
                release: false,
            })),
            handle: None,
        }
    }

    pub fn set_text(&mut self, text: String) {
        let mut s = self.state.lock().unwrap();
        s.text = text;
        s.version += 1;
        s.release = false;
        if self.handle.is_none() {
            let state = self.state.clone();
            self.handle = Some(thread::spawn(move || serve(state)));
        }
    }

    /// Give up ownership of the PRIMARY selection.
    ///
    /// After releasing, PRIMARY is *not* re-claimed until the user makes a
    /// genuinely new selection (i.e. `set_text` is called again).
    #[allow(dead_code)]
    pub fn release(&mut self) {
        if let Ok(mut s) = self.state.lock() {
            s.release = true;
        }
    }
}

/// Atoms used by the selection protocol, interned once at startup.
struct Atoms {
    targets: u32,
    timestamp: u32,
    multiple: u32,
    utf8: u32,
    string: u32,
    atom: u32,
    atom_pair: u32,
    time_dummy: u32,
}

fn intern(conn: &RustConnection, name: &[u8]) -> Option<u32> {
    conn.intern_atom(false, name)
        .ok()?
        .reply()
        .ok()
        .map(|r| r.atom)
}

fn make_atoms(conn: &RustConnection) -> Option<Atoms> {
    Some(Atoms {
        targets: intern(conn, b"TARGETS")?,
        timestamp: intern(conn, b"TIMESTAMP")?,
        multiple: intern(conn, b"MULTIPLE")?,
        utf8: intern(conn, b"UTF8_STRING")?,
        string: u32::from(AtomEnum::STRING),
        atom: u32::from(AtomEnum::ATOM),
        atom_pair: intern(conn, b"ATOM_PAIR")?,
        time_dummy: intern(conn, b"RUSTAMA_TIME")?,
    })
}

fn serve(state: Arc<Mutex<SelectionState>>) {
    let (conn, screen_num) = match x11rb::connect(None) {
        Ok(v) => v,
        Err(_) => return,
    };
    let screen = &conn.setup().roots[screen_num];

    let win = match conn.generate_id() {
        Ok(w) => w,
        Err(_) => return,
    };
    // PROPERTY_CHANGE is needed so we receive the PropertyNotify events
    // generated by our own zero-length appends (used to read server time).
    if conn
        .create_window(
            x11rb::COPY_DEPTH_FROM_PARENT,
            win,
            screen.root,
            0,
            0,
            1,
            1,
            0,
            WindowClass::INPUT_ONLY,
            x11rb::COPY_FROM_PARENT,
            &CreateWindowAux::new().event_mask(EventMask::PROPERTY_CHANGE),
        )
        .is_err()
    {
        return;
    }
    if conn.flush().is_err() {
        return;
    }

    let atoms = match make_atoms(&conn) {
        Some(a) => a,
        None => return,
    };

    let mut last_version: Option<u64> = None;
    let mut pending_grab = false;
    let mut owned = false;
    let mut owner_time: u32 = x11rb::CURRENT_TIME;

    loop {
        let (text, version, release) = {
            let s = match state.lock() {
                Ok(g) => g,
                Err(_) => return,
            };
            (s.text.clone(), s.version, s.release)
        };

        // Explicit release request: give up PRIMARY and do NOT re-claim it
        // for the current text. Only a genuinely new selection (a version
        // bump via set_text) may claim PRIMARY again.
        if release {
            if owned {
                if conn
                    .set_selection_owner(0u32, u32::from(AtomEnum::PRIMARY), x11rb::CURRENT_TIME)
                    .is_err()
                {
                    return;
                }
                if conn.flush().is_err() {
                    return;
                }
                owned = false;
            }
            // Mark this version as handled so the grab logic below skips it.
            last_version = Some(version);
            if let Ok(mut s) = state.lock() {
                s.release = false;
            }
        }

        // New text was selected by the user -> claim PRIMARY.
        //
        // ICCCM wants claims with a real timestamp (not CURRENT_TIME) to
        // avoid races, so we first obtain the server time by appending zero
        // bytes to a property on our own window; the resulting
        // PropertyNotify carries the timestamp and is handled in the event
        // loop below, where the actual set_selection_owner happens.
        //
        // CRITICAL FIX: the claim is triggered ONLY by a version change
        // (the user selected new text). Losing ownership (SelectionClear)
        // must NOT re-claim PRIMARY -- otherwise we endlessly steal the
        // selection back from every other X11 client (browser, terminal,
        // xclip, ...) and copy/paste breaks across the whole desktop.
        if last_version != Some(version) && !pending_grab {
            last_version = Some(version);
            if conn
                .change_property8(PropMode::APPEND, win, atoms.time_dummy, atoms.string, &[])
                .is_err()
            {
                return;
            }
            if conn.flush().is_err() {
                return;
            }
            pending_grab = true;
        }

        loop {
            let event = match conn.poll_for_event() {
                Ok(Some(e)) => e,
                Ok(None) => break,
                Err(_) => return,
            };
            match event {
                Event::SelectionRequest(req) => {
                    handle_selection_request(&conn, &req, &text, &atoms, owner_time);
                }
                Event::SelectionClear(_) => {
                    // Another client now owns PRIMARY. That is fine: the
                    // last user action wins. Just note that we no longer own
                    // it -- do NOT try to take it back.
                    owned = false;
                }
                Event::PropertyNotify(ev) => {
                    // Generated by our zero-length append: use its server
                    // timestamp to claim PRIMARY race-free (ICCCM 2.1).
                    if pending_grab {
                        pending_grab = false;
                        if conn
                            .set_selection_owner(win, u32::from(AtomEnum::PRIMARY), ev.time)
                            .is_err()
                        {
                            return;
                        }
                        if conn.flush().is_err() {
                            return;
                        }
                        owned = true;
                        owner_time = ev.time;
                        // The grab covers the current text, even if it
                        // changed while the append was in flight.
                        last_version = Some(version);
                    }
                }
                _ => {}
            }
        }

        thread::sleep(Duration::from_millis(50));
    }
}

fn handle_selection_request(
    conn: &RustConnection,
    req: &SelectionRequestEvent,
    text: &str,
    atoms: &Atoms,
    owner_time: u32,
) {
    // ICCCM 2.2: obsolete clients pass None as the property; the owner
    // should then store the data in a property named after the target.
    let property = if req.property == 0 {
        req.target
    } else {
        req.property
    };

    if req.target == atoms.multiple {
        handle_multiple(conn, req, property, text, atoms, owner_time);
        return;
    }

    if convert_target(
        conn,
        req.requestor,
        property,
        req.target,
        text,
        atoms,
        owner_time,
    ) {
        send_selection_notify(conn, req, property);
    } else {
        send_selection_notify(conn, req, 0);
    }
}

/// Store one converted target into `property` on the requestor.
/// Returns false if the target is unsupported or the write failed.
fn convert_target(
    conn: &RustConnection,
    requestor: u32,
    property: u32,
    target: u32,
    text: &str,
    atoms: &Atoms,
    owner_time: u32,
) -> bool {
    if target == atoms.targets {
        let supported = [
            atoms.targets,
            atoms.timestamp,
            atoms.multiple,
            atoms.utf8,
            atoms.string,
        ];
        conn.change_property32(
            PropMode::REPLACE,
            requestor,
            property,
            atoms.atom,
            &supported,
        )
        .is_ok()
    } else if target == atoms.timestamp {
        conn.change_property32(
            PropMode::REPLACE,
            requestor,
            property,
            u32::from(AtomEnum::INTEGER),
            &[owner_time],
        )
        .is_ok()
    } else if target == atoms.utf8 || target == atoms.string {
        conn.change_property8(
            PropMode::REPLACE,
            requestor,
            property,
            target,
            text.as_bytes(),
        )
        .is_ok()
    } else {
        false
    }
}

/// ICCCM MULTIPLE target: the requestor's property holds a list of
/// (target, property) atom pairs. Convert each in place; pairs whose
/// conversion failed get their property set to None.
fn handle_multiple(
    conn: &RustConnection,
    req: &SelectionRequestEvent,
    property: u32,
    text: &str,
    atoms: &Atoms,
    owner_time: u32,
) {
    let reply = match conn.get_property(false, req.requestor, property, 0u32, 0, 4096) {
        Ok(cookie) => cookie.reply().ok(),
        Err(_) => None,
    };

    let mut ok = false;
    if let Some(reply) = reply
        && let Some(values) = reply.value32()
    {
        let mut pairs: Vec<u32> = values.collect();
        for chunk in pairs.chunks_mut(2) {
            if chunk.len() != 2 {
                break;
            }
            let (t, p) = (chunk[0], chunk[1]);
            if p == 0 {
                continue;
            }
            if t == atoms.multiple {
                // Nested MULTIPLE is not allowed.
                chunk[1] = 0;
                continue;
            }
            if !convert_target(conn, req.requestor, p, t, text, atoms, owner_time) {
                chunk[1] = 0; // None: conversion failed
            }
        }
        ok = conn
            .change_property32(
                PropMode::REPLACE,
                req.requestor,
                property,
                atoms.atom_pair,
                &pairs,
            )
            .is_ok();
    }

    send_selection_notify(conn, req, if ok { property } else { 0 });
}

fn send_selection_notify(conn: &RustConnection, req: &SelectionRequestEvent, property: u32) {
    let ev = SelectionNotifyEvent {
        response_type: 31,
        sequence: 0,
        time: req.time,
        requestor: req.requestor,
        selection: req.selection,
        target: req.target,
        property,
    };
    if conn
        .send_event(false, req.requestor, EventMask::NO_EVENT, ev)
        .is_ok()
    {
        let _ = conn.flush();
    }
}
